### ISSUE TITLE
About the input data format

### ISSUE THREAD

**Issue by newera912** [phanein/amen#1]
Hi,
I have a question about the input data format. I have a graph with size of 100 ,undirected graph, and each node has 10 attributes. In AMEN function input parameter A is the adjacent matrix (100X100 double) and X is the attribute data matrix (100X10 double). But when I ran the code in matlab, it gives me errors. is this  data format problem or I misunderstanding the input parameter, Thank you.
Error Messages: 
??? Undefined function or method 'circle_boundary_undirected' for input arguments of
type 'double'.

Error in ==> amen_objective_learn_normalized at 18
    [boundary_nodes, B_internal, B_external, ~] = circle_boundary_undirected(A,
    community);

Error in ==> amen_objective_wrapper at 32
    [raw_score, data_score, ...

Error in ==> amen_learn_weights at 7
    [~, ~, data_score] = amen_objective_wrapper(A, X, community, weights, degrees,
    M, @amen_objective_learn_normalized, 1, X_Transpose);

Error in ==> amen_rank at 43
        [~, weighted_score] = amen_learn_weights( A, X, egonet_community, degrees,
        M, p_norm, @amen_objective, X_Total_Transpose );

Error in ==> example at 8
[amen_ranking, amen_scores] = amen_rank(A, X, 'norm', 'L2', 'min_degree', 1,
'max_degree', inf);

**Comment by phanein** [comment]
Hello @newera912 ,

In general, this seems like the right input format.  

What commit of the code do you have checked out?  (I recently switched support for continuous values in the attribute matrix to its [own branch](https://github.com/phanein/amen/tree/continuous))

What version of Matlab are you using to run this?  I think the error has to do with "circle_boundary_undirected" not being in your path.

**Comment by newera912** [comment]
Hi,  Thank you for reply.
I used the last updated version of your code. Matlab version is R2011a. 
But I can run the given dblp data use your example.m, but it takes a little longer time.

**Comment by newera912** [comment]
Hi, 
You are right, I changed the Matlab version 2011b to 2015b, now it works. Thanks your help.

**Comment by phanein** [comment]
Glad that worked.  I'm still not exactly sure what branch you are using, so I will leave this here for posterity -- if anyone is using continuous features, check out the continuous branch. https://github.com/phanein/amen/tree/continuous

**Comment by newera912** [comment]
Yes, I used the last updated branch 13 days ago. Thank you very much.
